### ISSUE TITLE
r-base probably unnecessarily pinned down

### ISSUE THREAD

**Issue by mbargull** [conda-forge/r-nasaaccess-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@imohamme, the `meta.yaml` has `- r-base =4.1` in the requirements section.
This prevents it from automatically picking the R version used for all other R packages on conda-forge.
It should just read `- r-base` without any version constraint (in both `host` and `run` requirements).
It will then be automatically built for the newer R 4.2 and future R versions.

**Comment by mfansler** [comment]
Resolved by #4
